target: com.longe.allstarhmt
auto_click: true
adb_ports:
  # - 16416  # MUMU模擬器
  - 5555   # 雷電模擬器
loops: 100
global_interval: 5

base_check_list:
  - 開始配對
  - 確認
  - 點擊空白區域繼續
  - 返回大廳
  - 返回大廳2
  - 等級提升
  - 重新連接確認
  - 返回
  - 已完成王朝
  - 切換遊戲
  - 選擇3v3
  - 選擇5v5
  - 選擇

additional_check_list:
  - null

image_list:
  - image_name: "開始配對"
    image_path: "./data/allstars/start.png"
    delay_after_click: 20
    screenshot_option: False
    confidence: 0.8

  - image_name: "點擊空白區域繼續"
    image_path: "./data/allstars/click2continue.png"
    delay_after_click: 0
    screenshot_option: False
    confidence: 0.8

  - image_name: "返回大廳"
    image_path: "./data/allstars/back2lobby.png"
    delay_after_click: 0
    screenshot_option: False
    confidence: 0.8

  - image_name: "確認"
    image_path: "./data/allstars/confirm.png"
    delay_after_click: 0
    screenshot_option: False
    confidence: 0.8

  - image_name: "等級提升"
    image_path: "./data/allstars/levelup.png"
    delay_after_click: 0
    screenshot_option: False
    confidence: 0.8

  - image_name: "重新連接確認"
    image_path: "./data/allstars/conmfirm4reconnect.png"
    delay_after_click: 0
    screenshot_option: False
    confidence: 0.8

  - image_name: "返回"
    image_path: "./data/allstars/back.png"
    delay_after_click: 0
    screenshot_option: False
    confidence: 0.8

  - image_name: "已完成王朝"
    image_path: "./data/allstars/game_limit.png"
    delay_after_click: 0
    screenshot_option: False
    confidence: 0.8

  - image_name: "切換遊戲"
    image_path: "./data/allstars/change_game_mode.png"
    delay_after_click: 0
    screenshot_option: False
    confidence: 0.8

  - image_name: "選擇3v3"
    image_path: "./data/allstars/select_3v3.png"
    delay_after_click: 0
    screenshot_option: False
    confidence: 0.8

  - image_name: "選擇5v5"
    image_path: "./data/allstars/select_5v5.png"
    delay_after_click: 0
    screenshot_option: False
    confidence: 0.8

  - image_name: "選擇"
    image_path: "./data/allstars/select_it.png"
    delay_after_click: 0
    screenshot_option: False
    confidence: 0.8
