target: com.longe.allstarhmt
save2db: True
auto_click: True
serials:
  - "16416"
random_interval: 5

image_list:
  - image_name: 開始配對
    image_path: ./data/allstars/start.png
    delay_after_click: 20
    click_this: True
    screenshot_option: True
    confidence: 0.8
    vertical: center
    horizontal: center

  - image_name: 點擊空白區域繼續
    image_path: ./data/allstars/click2continue.png
    delay_after_click: 1
    click_this: True
    screenshot_option: True
    confidence: 0.8
    vertical: center
    horizontal: center

  - image_name: 返回大廳
    image_path: ./data/allstars/back2lobby.png
    delay_after_click: 1
    click_this: True
    screenshot_option: True
    confidence: 0.8
    vertical: center
    horizontal: center

  - image_name: 確認
    image_path: ./data/allstars/confirm.png
    delay_after_click: 1
    click_this: True
    screenshot_option: True
    confidence: 0.8
    vertical: center
    horizontal: center

  - image_name: 等級提升
    image_path: ./data/allstars/levelup.png
    delay_after_click: 1
    click_this: True
    screenshot_option: True
    confidence: 0.8
    vertical: center
    horizontal: center

  - image_name: 返回
    image_path: ./data/allstars/back.png
    delay_after_click: 1
    click_this: True
    screenshot_option: True
    confidence: 0.8
    vertical: center
    horizontal: center

  - image_name: 已完成王朝
    image_path: ./data/allstars/game_limit.png
    delay_after_click: 1
    click_this: False
    screenshot_option: True
    confidence: 0.8
    vertical: center
    horizontal: center

  - image_name: 勝利
    image_path: ./data/allstars/win.png
    delay_after_click: 1
    click_this: False
    screenshot_option: True
    confidence: 0.8
    vertical: center
    horizontal: center

  - image_name: 失敗
    image_path: ./data/allstars/lose.png
    delay_after_click: 1
    click_this: False
    screenshot_option: True
    confidence: 0.8
    vertical: center
    horizontal: center

# switch_conditions:
#   - image_name: 確認
#     image_path: ./data/allstars/confirm.png
#     delay_after_click: 1
#     click_this: True
#     screenshot_option: True
#     confidence: 0.8
#     vertical: center
#     horizontal: center

#   - image_name: 打開切換選單
#     image_path: ./data/allstars/switch_game.png
#     delay_after_click: 2
#     click_this: True
#     screenshot_option: True
#     confidence: 0.6
#     vertical: center
#     horizontal: center
#     force_x: 1600
#     force_y: 630

#   - image_name: 五對五全場爭霸
#     image_path: ./data/allstars/game_5v5.png
#     delay_after_click: 2
#     click_this: True
#     screenshot_option: True
#     confidence: 0.6
#     vertical: bottom
#     horizontal: center
#     force_x: 1600
#     force_y: 830

#   - image_name: 點擊選擇
#     image_path: ./data/allstars/select.png
#     delay_after_click: 2
#     click_this: True
#     screenshot_option: True
#     confidence: 0.8
#     vertical: center
#     horizontal: center
#     force_x: 1600
#     force_y: 930
