target: 雀魂麻将  # "http://localhost:9222"
auto_click: true

global_interval: 5

image_list:
  - image_name: "開始段位"
    image_path: "./data/mahjong/ranking.png"
    delay_after_click: 0
    screenshot_option: False
    confidence: 0.9

  - image_name: "胡了"
    image_path: "./data/mahjong/hule.png"
    delay_after_click: 0
    screenshot_option: False
    confidence: 0.9

  - image_name: "對局結束"
    image_path: "./data/mahjong/match_end.png"
    delay_after_click: 0
    screenshot_option: False
    confidence: 0.9

  - image_name: "結算畫面"
    image_path: "./data/mahjong/score.png"
    delay_after_click: 0
    screenshot_option: True
    confidence: 0.9

  - image_name: "遊戲結束確認"
    image_path: "./data/mahjong/confirm.png"
    delay_after_click: 0
    screenshot_option: False
    confidence: 0.9

  - image_name: "遊戲結束確認2"
    image_path: "./data/mahjong/confirm2.png"
    delay_after_click: 0
    screenshot_option: False
    confidence: 0.9

  - image_name: "簽到"
    image_path: "./data/mahjong/assign_v2.png"
    delay_after_click: 0
    screenshot_option: False
    confidence: 0.9

  - image_name: "關閉"
    image_path: "./data/mahjong/turn_off.png"
    delay_after_click: 0
    screenshot_option: False
    confidence: 0.9

  - image_name: "叉叉"
    image_path: "./data/mahjong/xx.png"
    delay_after_click: 0
    screenshot_option: False
    confidence: 0.9

  - image_name: "進入遊戲"
    image_path: "./data/mahjong/login.png"
    delay_after_click: 0
    screenshot_option: False
    confidence: 0.9

  - image_name: "好的"
    image_path: "./data/mahjong/haode.png"
    delay_after_click: 0
    screenshot_option: False
    confidence: 0.9

  # 這段三選一
  - image_name: "一般場"
    image_path: "./data/mahjong/normal.png"
    delay_after_click: 5
    screenshot_option: False
    confidence: 0.9

  - image_name: "銅之間"
    image_path: "./data/mahjong/tong.png"
    delay_after_click: 0
    screenshot_option: False
    confidence: 0.9

  - image_name: "銀之間"
    image_path: "./data/mahjong/silver.png"
    delay_after_click: 0
    screenshot_option: False
    confidence: 0.9

  - image_name: "金之間"
    image_path: "./data/mahjong/gold.png"
    delay_after_click: 0
    screenshot_option: False
    confidence: 0.9

  - image_name: "玉之間"
    image_path: "./data/mahjong/yu.png"
    delay_after_click: 0
    screenshot_option: False
    confidence: 0.9

  - image_name: "王座之間"
    image_path: "./data/mahjong/king.png"
    delay_after_click: 0
    screenshot_option: False
    confidence: 0.9

  # 這段二選一
  - image_name: "四人東"
    image_path: "./data/mahjong/east_4p.png"
    delay_after_click: 30
    screenshot_option: False
    confidence: 0.9

  - image_name: "四人南"
    image_path: "./data/mahjong/south_4p.png"
    delay_after_click: 30
    screenshot_option: False
    confidence: 0.9

  - image_name: "三人東"
    image_path: "./data/mahjong/east_3p.png"
    delay_after_click: 30
    screenshot_option: False
    confidence: 0.95

  - image_name: "三人南"
    image_path: "./data/mahjong/south_3p.png"
    delay_after_click: 30
    screenshot_option: False
    confidence: 0.9
