auto_click: true

base_check_list:
  - 遊戲結束確認
  - 遊戲結束確認2
  - 開始段位
  - 胡了
  - 對局結束
  - 結算畫面
  - 簽到
  - 關閉
  - 叉叉
  - 進入遊戲
  - 好的

additional_check_list:
  - 玉之間
  - 四人南

image_list:
  - image_name: "開始段位"
    image_path: "./data/mahjong/ranking.png"
    image_click_delay: 0
    screenshot_option: False
    confidence: 0.9
    scroll: 0

  - image_name: "胡了"
    image_path: "./data/mahjong/hule.png"
    image_click_delay: 0
    screenshot_option: False
    confidence: 0.9
    scroll: 0

  - image_name: "對局結束"
    image_path: "./data/mahjong/match_end.png"
    image_click_delay: 0
    screenshot_option: False
    confidence: 0.9
    scroll: 0

  - image_name: "結算畫面"
    image_path: "./data/mahjong/score.png"
    image_click_delay: 0
    screenshot_option: True
    confidence: 0.9
    scroll: 0

  - image_name: "遊戲結束確認"
    image_path: "./data/mahjong/confirm.png"
    image_click_delay: 0
    screenshot_option: False
    confidence: 0.9
    scroll: 0

  - image_name: "遊戲結束確認2"
    image_path: "./data/mahjong/confirm2.png"
    image_click_delay: 0
    screenshot_option: False
    confidence: 0.9
    scroll: 0

  - image_name: "簽到"
    image_path: "./data/mahjong/assign_v2.png"
    image_click_delay: 0
    screenshot_option: False
    confidence: 0.9
    scroll: 0

  - image_name: "關閉"
    image_path: "./data/mahjong/turn_off.png"
    image_click_delay: 0
    screenshot_option: False
    confidence: 0.9
    scroll: 0

  - image_name: "叉叉"
    image_path: "./data/mahjong/xx.png"
    image_click_delay: 0
    screenshot_option: False
    confidence: 0.9
    scroll: 0

  - image_name: "進入遊戲"
    image_path: "./data/mahjong/login.png"
    image_click_delay: 0
    screenshot_option: False
    confidence: 0.9
    scroll: 0

  - image_name: "好的"
    image_path: "./data/mahjong/haode.png"
    image_click_delay: 0
    screenshot_option: False
    confidence: 0.9
    scroll: 0

  # 這段三選一
  - image_name: "一般場"
    image_path: "./data/mahjong/normal.png"
    image_click_delay: 5
    screenshot_option: False
    confidence: 0.9
    scroll: -100

  - image_name: "銅之間"
    image_path: "./data/mahjong/tong.png"
    image_click_delay: 0
    screenshot_option: False
    confidence: 0.9
    scroll: 0

  - image_name: "銀之間"
    image_path: "./data/mahjong/silver.png"
    image_click_delay: 0
    screenshot_option: False
    confidence: 0.9
    scroll: 0

  - image_name: "金之間"
    image_path: "./data/mahjong/gold.png"
    image_click_delay: 0
    screenshot_option: False
    confidence: 0.9
    scroll: 0

  - image_name: "玉之間"
    image_path: "./data/mahjong/yu.png"
    image_click_delay: 0
    screenshot_option: False
    confidence: 0.9
    scroll: 0

  - image_name: "王座之間"
    image_path: "./data/mahjong/king.png"
    image_click_delay: 0
    screenshot_option: False
    confidence: 0.9
    scroll: 0

  # 這段二選一
  - image_name: "四人東"
    image_path: "./data/mahjong/east_4p.png"
    image_click_delay: 30
    screenshot_option: False
    confidence: 0.9
    scroll: 0

  - image_name: "四人南"
    image_path: "./data/mahjong/south_4p.png"
    image_click_delay: 30
    screenshot_option: False
    confidence: 0.9
    scroll: 0

  - image_name: "三人東"
    image_path: "./data/mahjong/east_3p.png"
    image_click_delay: 30
    screenshot_option: False
    confidence: 0.95
    scroll: 0

  - image_name: "三人南"
    image_path: "./data/mahjong/south_3p.png"
    image_click_delay: 30
    screenshot_option: False
    confidence: 0.9
    scroll: 0
