- image_name: "遊戲結束確認"
  image_path: "./data/samples/confirm.png"
  image_click_delay: 0
  screenshot_option: True

- image_name: "開始段位"
  image_path: "./data/samples/ranking.png"
  image_click_delay: 0
  screenshot_option: False

- image_name: "銀之間"
  image_path: "./data/samples/silver.png"
  image_click_delay: 0
  screenshot_option: False

- image_name: "四人東"
  image_path: "./data/samples/play_start.png"
  image_click_delay: 30
  screenshot_option: False

- image_name: "胡了"
  image_path: "./data/samples/hule.png"
  image_click_delay: 0
  screenshot_option: True

- image_name: "對局結束"
  image_path: "./data/samples/match_end.png"
  image_click_delay: 0
  screenshot_option: True

- image_name: "獲得獎勵"
  image_path: "./data/samples/reward_gain.png"
  image_click_delay: 0
  screenshot_option: False

- image_name: "簽到v1"
  image_path: "./data/samples/assign_v1.png"
  image_click_delay: 0
  screenshot_option: False

- image_name: "簽到v2"
  image_path: "./data/samples/assign_v2.png"
  image_click_delay: 0
  screenshot_option: False

- image_name: "關閉"
  image_path: "./data/samples/turn_off.png"
  image_click_delay: 0
  screenshot_option: False

- image_name: "叉叉"
  image_path: "./data/samples/xx.png"
  image_click_delay: 0
  screenshot_option: False

- image_name: "登入"
  image_path: "./data/samples/turn_off.png"
  image_click_delay: 0
  screenshot_option: False

- image_name: "好的"
  image_path: "./data/samples/haode.png"
  image_click_delay: 0
  screenshot_option: False
