- image_name: "遊戲結束確認"
  image_path: "./data/samples/confirm.png"
  image_click_delay: 0
  screenshot_option: True

- image_name: "開始段位"
  image_path: "./data/samples/ranking.png"
  image_click_delay: 0
  screenshot_option: False

- image_name: "銅之間"
  image_path: "./data/samples/tong.png"
  image_click_delay: 0
  screenshot_option: False

- image_name: "四人東"
  image_path: "./data/samples/play_start.png"
  image_click_delay: 5
  screenshot_option: False

- image_name: "胡了"
  image_path: "./data/samples/hule.png"
  image_click_delay: 0
  screenshot_option: True
