# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Build Executable File

on:
  pull_request:
    branches:
      - master
  push:
    tags:
      - v*

permissions: write-all

jobs:
  build_package:
    name: Build Executable File
    runs-on: windows-latest

    steps:
      - name: Disable SSL Verify
        run: git config --global http.sslVerify false

      - name: Checkout
        uses: actions/checkout@v4.1.2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.10'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Packaging to Executable file
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pyinstaller -F main.py --onefile -n auto_clicker

      - name: Move and Rename
        shell: pwsh
        run: |
          Move-Item -Path ./configs -Destination ./dist/
          Move-Item -Path ./src -Destination ./dist/
          Move-Item -Path ./data -Destination ./dist/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: auto_clicker
          path: ./dist/
          if-no-files-found: ignore
          retention-days: 1
          compression-level: 6
          overwrite: true

      - name: List All Files
        shell: pwsh
        run: |
          Get-ChildItem -Path .

      - name: Release Drafter
        uses: release-drafter/release-drafter@v6
        id: drafter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config-name: release-drafter.yml
          publish: false
          disable-autolabeler: true

      - name: Show upload url
        run: echo ${{ steps.drafter.outputs.upload_url }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.drafter.outputs.upload_url }}
          asset_path: ./auto_clicker.zip
          asset_name: auto_clicker.zip
          asset_content_type: application/zip
